"""Database-backed authentication services for the single operator."""

from gods_watching.contracts.identifiers import LoginSessionId

from .passwords import (
    Password,
    PasswordPolicyError,
    SecretFileError,
    generate_password,
    hash_password,
    parse_password,
    read_password_file,
    verify_password,
)
from .policy import (
    ClientIpError,
    MutationOriginError,
    canonical_client_ip,
    is_same_origin,
    require_same_origin,
)
from .repository import (
    CredentialStorageError,
    CredentialStore,
    SqlAlchemyCredentialStore,
    TransactionProvider,
    lock_auth_namespace,
)
from .service import (
    ABSOLUTE_TIMEOUT,
    CLEANUP_INTERVAL_SECONDS,
    IDLE_TIMEOUT,
    AuthService,
    UtcClock,
)
from .throttle import IpLoginThrottle
from .types import (
    Authenticated,
    AuthenticationFailure,
    AuthenticationFailureReason,
    AuthenticationResult,
    ClientIp,
    Clock,
    ClockError,
    InvalidCredentials,
    LoginAccepted,
    LoginAttempt,
    LoginResult,
    LoginThrottled,
    NoopRevocationHook,
    PasswordReplacement,
    SessionRevocation,
    SessionRevocationHook,
    SessionRevocationReason,
    SessionToken,
    SessionView,
)

__all__ = [
    "ABSOLUTE_TIMEOUT",
    "CLEANUP_INTERVAL_SECONDS",
    "IDLE_TIMEOUT",
    "AuthService",
    "Authenticated",
    "AuthenticationFailure",
    "AuthenticationFailureReason",
    "AuthenticationResult",
    "ClientIp",
    "ClientIpError",
    "Clock",
    "ClockError",
    "CredentialStorageError",
    "CredentialStore",
    "InvalidCredentials",
    "IpLoginThrottle",
    "LoginAccepted",
    "LoginAttempt",
    "LoginResult",
    "LoginSessionId",
    "LoginThrottled",
    "MutationOriginError",
    "NoopRevocationHook",
    "Password",
    "PasswordPolicyError",
    "PasswordReplacement",
    "SecretFileError",
    "SessionRevocation",
    "SessionRevocationHook",
    "SessionRevocationReason",
    "SessionToken",
    "SessionView",
    "SqlAlchemyCredentialStore",
    "TransactionProvider",
    "UtcClock",
    "canonical_client_ip",
    "generate_password",
    "hash_password",
    "is_same_origin",
    "lock_auth_namespace",
    "parse_password",
    "read_password_file",
    "require_same_origin",
    "verify_password",
]
